name: Hello World

on:
  push:
    branches:
      - '*'

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 

      - name: 
        run: |
          ls
          pwd
          cd ouroborus
          pwd
          ls
          ruby --version