name: Publish Ouroborus Gem

on:
  push:
    branches:
      - '*'

jobs:
  publish-gem:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 

      - name: Publish Ouroborus Gem to GitHub Registry
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n:rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          ls -a ~
          ls -a ~/.gem
          cat ~/.gem/credentials
          cd ouroborus
          pwd
          gem build ouroborus.gemspec



          #echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > .gem/credentials
          #ls -a
          # gem push --key github --host https://rubygems.pkg.github.com/uxjp/self-deployable-docker ouroborus*.gem
