name: Hello World

on:
  push:
    branches:
      - '*'

jobs:
  publish-gem:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Print Hello World
        run: |
          ls
          pwd