name: Hello World

on:
  push:
    branches:
      - '*'

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: |
          pwd
          cd ouroborus
          pwd
          ls